name: 'Move Stale Issues'
description: 'Move stale issues to a milestone'
author: 'Deividy'
inputs:
  repo-token:
    description: 'Token for the repo. The usual secrets.GITHUB_TOKEN'
    required: true

  from-milestone:
    description: 'From milestone to move the issues'
    required: false

  target-milestone:
    description: 'Target milestone to move the issues'
    required: true

  days-before-stale:
    description: 'The total of days we consider an issue stale'
    required: false
    default: 30

runs:
  using: 'node16'
  main: 'dist/move-stale-issues.js'
